#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    glib-compile-schemas /usr/share/glib-2.0/schemas || true
    if command -v gtk-update-icon-cache >/dev/null 2>&1; then
        gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || true
    fi
    if command -v update-desktop-database >/dev/null 2>&1; then
        update-desktop-database -q /usr/share/applications || true
    fi
fi

#DEBHELPER#
